### ISSUE TITLE
Making it a header-only library?

### ISSUE THREAD

**Issue by hjk41** [dmlc/dmlc-core#105]
Is there any specific reason why we didn't make it a header-only library? I think a header-only library is much easier to integrate into other projects.

**Comment by tqchen** [comment]
I made an a attempt to do so in here https://github.com/dmlc/xgboost/blob/master/amalgamation/dmlc-minimum0.cc

I think the general idea of creating an amalgamation option is great for portability. However, the code can still be organized as it is.

**Comment by tqchen** [comment]
closing for now
