### ISSUE TITLE
[Discussion] Unified Tracker

### ISSUE THREAD

**Issue by tqchen** [dmlc/dmlc-core#111]
This is the proposal for a unified tracker script that is used to launch all DMLC jobs. I will post all the necessary parameters here, and please respond the discussion if we want to iterate. Previously the tracker script of DMLC job submission has been separated into different python files. While this can be convenient, it also makes user hard to find a central command instruction  to submit all kinds of jobs. So I am proposing a new centralized script `dmlc-submit` that will submit the jobs.

This discussion thread will eventually becomes the document as well as spec for the submission script. I am hoping we can do it in one to two weeks

Let us also discuss parameters, I think we could avoid using abbreviations and enforce full names, to make submission script more clear, as in other job submission scripts like 

Some of these parameters could be set from environment variables, with prefix DMLC.
## Parameters
- `--num-workers` integer, required
  - Number of workers in the job.
- `--num-servers`` integer, default 0. Number of servers in the job.
- `--worker-cores` integer, default 1 . Number of cores needed to be allocated for worker job.
- `--server-cores` integer, default 1, Number of cores needed to be allocated for server job.
- `--worker-memory` string, integer + [g|m], default 1g, Memory needed for worker job.
- `--server-memory` string, integer + [g|m], default 1g, Memory needed for worker job.
- `--mode` string, 'mpi' or 'yarn' or 'local', default to ${DMLC_SUBMIT_MODE}, submission mode.

**Comment by tqchen** [comment]
@mli @hjk41

**Comment by hjk41** [comment]
https://bitbucket.org/hjk41/popcorn
This is the Yarn code we are using to start different jobs on our clusters,
including MPI jobs and some other parameter server applications. We are
still working actively to improve it. If you are interested, I think we can
make it part of DMLC.

On Sun, Feb 21, 2016 at 12:54 AM, Tianqi Chen <notifications@github.com>
wrote:

> @mli <https://github.com/mli> @hjk41 <https://github.com/hjk41>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/dmlc-core/issues/111#issuecomment-186650758>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by tqchen** [comment]
@hjk41  It seems to be interesting. I think the goal is to make one unified tracker that handles most job  submission tasks. And make one application master that satisfies all the jobs. 

If what you did was general and works for all types of YARN env, I think it might be interesting to incorporate your code into current dmlc's tracker and YARN script, so we can combine force together on this.

**Comment by seusofthd** [comment]
For yarn, we also have to specify the resource manager ip and the yarn-script location, I don't know whether these parameters should also be specified or noot in mpi

**Comment by tqchen** [comment]
Yes, we will definitely have some arguments specific for YARN. The point of unified submission script is more for clear documentation, and user know where to start with in the first place

**Comment by tqchen** [comment]
I have make a refactor in https://github.com/tqchen/dmlc-core/tree/master/tracker

Some of the arguments are not backward compatible and moved to full name instead of abbrevation. Have not yet tested YARN mode, will run a test tomorrow. Comments are welcomed

**Comment by tqchen** [comment]
Opened PR here https://github.com/dmlc/dmlc-core/pull/113

**Comment by tqchen** [comment]
I have tested on xgboost jobs. @seusofthd  Can you help testing the new tracker on mxnet jobs?

**Comment by seusofthd** [comment]
Is it ok to just test yarn and local mode? We do not have the environment for openmpi, sge and mpich2.

**Comment by tqchen** [comment]
yes yarn and local are fine

**Comment by tqchen** [comment]
@seusofthd YARN and local mode should be fine, also please update your tutorial to the new arguments after it is merged:)

**Comment by seusofthd** [comment]
Ok, I will update it tomorrow. These two days we are catching up with a
product deadline.
