### ISSUE TITLE
AppMaster Kill Job Even if it finishes Normally

### ISSUE THREAD

**Issue by tqchen** [dmlc/dmlc-core#114]
see https://github.com/dmlc/xgboost/issues/879 I also observe this in my experiments. This was introduced in https://github.com/dmlc/dmlc-core/blob/master/tracker/yarn/src/main/java/org/apache/hadoop/yarn/dmlc/Client.java#L273

@seusofthd  Please look into it and submit a fix. I think we need to add a hook only for signal events such as ctrl +c but not normal shutdown

**Comment by seusofthd** [comment]
Let me take a look
