### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [dmlc/dmlc-core#13]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [DiskRowIter](https://github.com/dmlc/dmlc-core/blob/1ab850b2c6d1e0dbf317348585eaf3f536a426ff/src/data/disk_row_iter.h#L52 "Destructor for DiskRowIter")
* [ThreadedInputSplit](https://github.com/dmlc/dmlc-core/blob/9d1a6965ac2965027883ff7b03bf2e380af397ee/src/io/threaded_input_split.h#L41 "Destructor for ThreadedInputSplit")
* [ThreadedParser](https://github.com/dmlc/dmlc-core/blob/1ab850b2c6d1e0dbf317348585eaf3f536a426ff/src/data/parser.h#L81 "Destructor for ThreadedParser")

**Comment by mli** [comment]
fixed, thanks:)

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/dmlc/dmlc-core/commit/5cd3d2749058cbbafab627d7f1c7499860c6d219 "Deletion of a few unnecessary checks").
