### ISSUE TITLE
tracker script waiting indefinitely even after successful exit of yarn 

### ISSUE THREAD

**Issue by iamvamsi** [dmlc/dmlc-core#136]
Submitting using the dmlc-submit script is resulting in the successful spawning and completion of the job on yarn, but the dmlc-submit.py script is waiting indefinitely. The stack trace generated by killing at that point is resulting in the following stack trace : 

File "./tracker/dmlc-submit", line 9, in <module>
    submit.main()
  File "/idn/home/vdevabat/workingDir/tracker/dmlc_tracker/submit.py", line 46, in main
    yarn.submit(args)
  File "/idn/home/vdevabat/workingDir/tracker/dmlc_tracker/yarn.py", line 123, in submit
    pscmd=(' '.join([YARN_BOOT_PY] + args.command)))
  File "/idn/home/vdevabat/workingDir/tracker/dmlc_tracker/tracker.py", line 413, in submit
    rabit.join()
  File "/idn/home/vdevabat/workingDir/tracker/dmlc_tracker/tracker.py", line 329, in join
    self.thread.join(100)
  File "/usr/lib64/python2.6/threading.py", line 655, in join
    self.__block.wait(delay)
  File "/usr/lib64/python2.6/threading.py", line 258, in wait
    _sleep(delay)

Env : Mapr version of hadoop 2.5.1 is being used. The error is reproducible on the basic.cc file provided as a part of documentation. Any help appreciated.

**Comment by coder-james** [comment]
@iamvamsi have you solved this problem?

**Comment by iamvamsi** [comment]
No, not in the correct way. But I found the below hack to make a work around.
////// See the line before SKIPPING JOIN is getting printed.

<img width="771" alt="screen shot 2016-08-10 at 4 15 31 pm" src="https://cloud.githubusercontent.com/assets/1460677/17551100/ca295dc0-5f15-11e6-9005-585231813a0c.png">

**Comment by coder-james** [comment]
i ran train_mnist.py with ssh, 2 workers, 2 servers, and PSTracker in tracker.py worked, so i think the cause may be dmlc-yarn.jar with ps or wrong script arguments i set, i got a little confused with launcher.py and dmlc-submit arguments. Still try to figure it out...you started rabit tracker in another thread, but shouldn't rabit and ps be used separately? Anyway, Thank U!

**Comment by formath** [comment]
@iamvamsi Have you solved this problem?

**Comment by iamvamsi** [comment]
No @formath : I haven't looked at it, after the last comment and i'll try to let you know if there is an update.

**Comment by formath** [comment]
@tqchen I have also encountered this problem. Do you have any suggestions? Thanks.

**Comment by tqchen** [comment]
close due to inactivity
