### ISSUE TITLE
compile error with include/dmlc/json.h in mxnet

### ISSUE THREAD

**Issue by xlvector** [dmlc/dmlc-core#147]
I find this file changed 15 hours ago and this change may cause mxnet build error:

In file included from /usr/include/c++/4.8/typeindex:35:0,
                 from /dl/xlvector/mxnet/dmlc-core/include/dmlc/./json.h:19,
                 from /dl/xlvector/mxnet/dmlc-core/include/dmlc/parameter.h:22,
                 from include/mxnet/base.h:12,
                 from src/ndarray/./ndarray_function.h:11,
                 from src/ndarray/ndarray_function.cu:9:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the

**Comment by xlvector** [comment]
reset dmlc-core to 5c0efa5dbe3e70cdb6c4971ed1149041b7f57d25 can solve this error

**Comment by tqchen** [comment]
can you see if https://github.com/dmlc/dmlc-core/issues/147 fixes the issue?

**Comment by xlvector** [comment]
fixed
