### ISSUE TITLE
use wildcard directory get error

### ISSUE THREAD

**Issue by zhangruichang** [dmlc/dmlc-core#163]
include/dmlc/logging.h:245: [08:12:44] src/io/hdfs_filesys.cc:156: Check failed: files != NULL Error when ListDirectory /directory/_/train.gz terminate called after throwing an instance of 'dmlc::Error' what():  [08:12:44] src/io/hdfs_filesys.cc:156: Check failed: files != NULL Error when ListDirectory /directory/_/train.gz

http://doc.mapr.com/pages/viewpage.action?pageId=29658211

maybe hdfsListDirectory() does not support wildcard in directory, could we support this feature?

**Comment by muyinanhai** [comment]
Same problem. there are two files in "data" directory

include/dmlc/logging.h:208: [05:28:24] src/io/hdfs_filesys.cc:143: Check failed: files != NULL Error when ListDirectory hdfs://10.0.0.26/data
terminate called after throwing an instance of 'dmlc::Error'
  what():  [05:28:24] src/io/hdfs_filesys.cc:143: Check failed: files != NULL Error when ListDirectory hdfs://10.0.0.26/data
Aborted (core dumped)
Exception in thread Thread-1:

**Comment by tqchen** [comment]
you should be able to use regex for matching files
