### ISSUE TITLE
hdfs accessing with ip and port 

### ISSUE THREAD

**Issue by chenjx1005** [dmlc/dmlc-core#175]
I use ImageRecordIter to access the `val.rec` in hdfs, like `val =mx.io.ImageRecordIter(path_imgrec = "hdfs://address:54310/data_dir/val.rec",` 
however the error log is :`Exception in thread "main" java.io.IOException: Incomplete HDFS URI, no host: hdfs://address:54310:0`
I track the code and it seems whether the address has a port is ignored, and a port 0 is added. Is this a bug?
 this is the related issue i found:
https://github.com/dmlc/dmlc-core/pull/81

**Comment by chenjx1005** [comment]
@sharkdtu

**Comment by sharkdtu** [comment]
I checkd the libhdfs api docs and related sources. When the port is set 0, it will be ignored. You can check your hdfs-c api docs and sources, Maybe it is different from apache hadoop-hdfs.

**Comment by chenjx1005** [comment]
Yes. The api of my hdfs is different. So I will just change the code in my own branch. Thank you. @sharkdtu
