### ISSUE TITLE
JSON: Add function AddIndent() 

### ISSUE THREAD

**Issue by AbdealiJK** [dmlc/dmlc-core#182]
I've had instances where I would like to first generate a JSON object in one function and then embed this into a array in another JSON object.

In such cases, I do something like:
```C
    dmlc::JSONWriter writer(&os);
    writer.BeginArray();
    for (size_t i = 0; i < dump.size(); ++i) {
      if (i != 0) writer.WriteArraySeperator();
      os << dump[i];  // Dump the previously generated JSON here
    }
    writer.EndArray();
```
But this means the indenting is not right anymore. Would be nice to be able to fix the indenting with:
```C
    dmlc::JSONWriter writer(&os);
    writer.BeginArray();
    for (size_t i = 0; i < dump.size(); ++i) {
      if (i != 0) writer.WriteArraySeperator();
      os << dmlc::JSONWriter.AddIndent(dump[i], 1);  // Dump the previously generated JSON here
    }
    writer.EndArray();
```
or something similar

**Comment by szha** [comment]
IMO the JSONWriter shouldn't handle indentation in default setting. The size would be smaller.
