### ISSUE TITLE
Classification using mxnet in R --- factors need to be transformed to indicators in format 0, 1, 2 ,..., p

### ISSUE THREAD

**Issue by thengl** [dmlc/dmlc-core#184]
I have tested using your package for mapping soil types (geographical data). I was first simply using 'factor' format for the `train.y`, but then realized that predict will also add class `'0'` (basically missing values). After I [converted factors to integers](https://github.com/ISRICWorldSoil/GSIF_tutorials/blob/master/eberg/soilmaps_MLA.R#L78) (0,1,2,..,p) the maps were fine.

I have installed R package from [source code](https://github.com/dmlc/dmlc-core/issues/144). It is a pity that it is not also available via CRAN. Otherwise, thanks for such a great package!

**Comment by nmatare** [comment]
@thengl  thanks for commenting; this was really confusing me
