### ISSUE TITLE
Hi，could you make the class in www.imooc.com

### ISSUE THREAD

**Issue by lokenetwork** [dmlc/dmlc-core#19]
The introduce is important for the new people,say how to use it.
like the fis, fis is baidu product.
http://www.imooc.com/learn/220

**Comment by hjk41** [comment]
Thanks loken for the suggestion.

Unfortunately we don't have much time for recording tutorial for now.
Recording good videos takes a lot of effort.

We do encourage anyone to give any kind of tutorial on DMLC and its
sub-projects. If you are interested, you can try to give tutorial on immoc,
and we will give you as much help as we can.

On Fri, Jun 12, 2015 at 1:14 PM, loken <notifications@github.com> wrote:

> The introduce is important for the new people,say how to use it.
> like the fis, fis is baidu product.
> http://www.imooc.com/learn/220
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/dmlc-core/issues/19>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia
