### ISSUE TITLE
Something wrong in test/iostream_test.cc

### ISSUE THREAD

**Issue by shenpengjianke** [dmlc/dmlc-core#211]
Here is the suspected code snippets：
> int main(int args, char *argv[]) {
	if (argc < 2) {
		printf("Usage: <filename>\n");
		return 0;
	}
	dmlc::Stream *fs = dmlc::Stream::Create(argv[1], "w");
	dmlc::ostream os(fs);
	os << "hello-world" << 1e-10 << std::endl;
	delete fs;
}

fs is a pointer. When os is destructed, it call its member variable stream_, which stream_ = fs.
So if we delete fs before os is destructed, as above code shows, it will case dangling pointer.
I suggest delete fs in dmlc::ostream's destructor.

**Comment by tqchen** [comment]
You are write, os must get destructed before fs get destructed. deleting fs will change the behavior of the filesystem API though.

**Comment by tqchen** [comment]
you are more than welcomed to push a fix. Usually we simply put os in another scope.
