### ISSUE TITLE
S3 File API when reading a lot of files: Error - failed: data.str() == "false" the returning list is truncated

### ISSUE THREAD

**Issue by hvivani** [dmlc/dmlc-core#223]
## Environment info

Operating System: Linux ip-172-24-234-227 4.4.35-33.55.amzn1.x86_64

Compiler:
gcc version 4.8.3 20140911
Package used (python/R/jvm/C++):
C++

xgboost version used:
0.6

If installing from source, please provide

    The commit hash (git rev-parse HEAD)
    Logs will be helpful (If logs are large, please upload as attachment).

If you are using python package, please provide

    The python version and distribution
    The command to install xgboost if you are not installing from source

If you are using R package, please provide

    The R sessionInfo()
    The command to install xgboost if you are not installing from source
    /xgboost $ make JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.29.amzn1.x86_64

## Steps to reproduce

    $ ./xgboost/dmlc-core/test/filesys_test s3:///
    dmlc-submit < submit yarn job >

## What have you tried?

    We tested on 757, each with size 550MB and it worked
    It failed on 7437, each with size 550MB

## Summary of the issue:
when listing a bucket with large number of objects, this is the exception visible:

    src/io/s3_filesys.cc:792: Check failed: data.str() == "false" the returning list is truncated
    terminate called after throwing an instance of 'dmlc::Error'
    what(): [16:18:17] src/io/s3_filesys.cc:792: Check failed: data.str() == "false" the returning list is truncated
    End of LogType:stderr

As far as we can see, the error comes from:
https://github.com/dmlc/dmlc-core/blob/master/src/io/s3_filesys.cc#L834
where the XML structure being built is returned truncated. Mostly related to the large number of objects.

**Comment by hvivani** [comment]
As far as I can see, the issue arise when listing more than 1000 objects:

With 1000 objects:

    ../filesys_test ls s3://[my-bucket]/many_files_1000/
    /many_files_1000/bspl0001.c	0	is_dir=0
...
    /many_files_1000/bspl1000.c	0	is_dir=0

With 1001 objects:

    ../filesys_test ls s3://[my-bucket]/many_files_1001/
    [17:35:21] include/dmlc/logging.h:235: [17:35:21] src/io/s3_filesys.cc:792: Check failed: data.str() == "false" the returning list is truncated
    terminate called after throwing an instance of 'dmlc::Error'
    what():  [17:35:21] src/io/s3_filesys.cc:792: Check failed: data.str() == "false" the returning list is truncated 
    Aborted

**Comment by hvivani** [comment]
So basically, what is happening here is:
S3 will return a MAX of 1000 objects per request. 
After that limit the response will be IsTruncated == true). 
But the response also includes the NextContinuationToken element, the value of which we should use in the next request as the continuation-token to list the next set of objects. 
http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

**Comment by tqchen** [comment]
Yes, a patch is welcomed if you can help extend the API to deal with this case.

**Comment by liusztc09** [comment]
Hi @tqchen,

Here is a patch for the s3 paging issue. I worked with @hvivani and tested the fix with over 70000 files.

Not able to make a pull request to this repo.
Please see my personal branch:
https://github.com/liusztc09/dmlc-core-liu/pull/1/commits/5552bdcba9861017fb0b41d274d77fbd45ba73e8

**Comment by hdemers** [comment]
I'm very interested in seeing this patch being merged in. @liusztc09 would you be able to make a pull request to this repo now?
