### ISSUE TITLE
Modernize ThreadLocal

### ISSUE THREAD

**Issue by tqchen** [dmlc/dmlc-core#230]
see https://github.com/dmlc/xgboost/issues/2109

We should consider to directly use the thread_local keyword to create object when it is supported. We used  the old way mainly for windows compatibility. But we can just double check if latest MSVC support thread local object. Specifically, if we can do with non-trivial destructor. I do not have an windows machine @sxjscience can you help check this?

```c++
thread_local Object my_thread_singleton;
```

**Comment by tqchen** [comment]
Checked things online, seems it is supported after VS2015 but not in VS2013

**Comment by sxjscience** [comment]
I've tested the code in http://en.cppreference.com/w/cpp/language/storage_duration on VS2015 Community Update 3 and it works fine.
```c++
#include <iostream>
#include <string>
#include <thread>
#include <mutex>
 
thread_local unsigned int rage = 1; 
std::mutex cout_mutex;
 
void increase_rage(const std::string& thread_name)
{
    ++rage; // modifying outside a lock is okay; this is a thread-local variable
    std::lock_guard<std::mutex> lock(cout_mutex);
    std::cout << "Rage counter for " << thread_name << ": " << rage << '\n';
}
 
int main()
{
    std::thread a(increase_rage, "a"), b(increase_rage, "b");
 
    {
        std::lock_guard<std::mutex> lock(cout_mutex);
        std::cout << "Rage counter for main: " << rage << '\n';
    }
 
    a.join();
    b.join();
}
```
Output:
```
Rage counter for a: 2
Rage counter for main: 1
Rage counter for b: 2
```

**Comment by tqchen** [comment]
I see, can we define a macro to test VS version bigger than 2015?

**Comment by tqchen** [comment]
I made a PR here https://github.com/dmlc/dmlc-core/pull/232
