### ISSUE TITLE
Error when running local tracker

### ISSUE THREAD

**Issue by ericzhang-cn** [dmlc/dmlc-core#237]
when execute local.py, error occurred:

  File "dmlc_tracker/local.py", line 10, in <module>
    from . import tracker
ValueError: Attempted relative import in non-package

**Comment by hcho3** [comment]
`local.py` is not meant to be run directly. You should run it through `dmlc-submit`:
```
./tracker/dmlc-submit --cluster=local --num-workers=2 ...
```
