### ISSUE TITLE
Error message in stdout

### ISSUE THREAD

**Issue by weixuanfu2016** [dmlc/dmlc-core#256]
From [the issue 449](https://github.com/rhiever/tpot/issues/449) in TPOT,  we found xgboost python api could print out error message in stdout. The message would not show up once we turn off stdout buffering. It should be related to the [source codes](https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/logging.h#L235-L247). I think it is more reasonable to redirect the error message to stderr.

**Comment by tqchen** [comment]
stdostringstream does not print to stdout, it is the log function of customize printer that does this behavior. Since the custom logging is not error message, so xgboost chooses to log to stdout.

**Comment by tqchen** [comment]
as explained it is not issue in dmlc-core, so i will close this issue

**Comment by weixuanfu2016** [comment]
Thank you for the explanation. Is there any way to let xgboost not log to stdout?
