### ISSUE TITLE
Something wrong in json.h

### ISSUE THREAD

**Issue by xianbincheng** [dmlc/dmlc-core#270]
std::ostringstream os;
    ch = is_->get();
    if (ch == '\\') {
      char sch = static_cast<char>(is_->get());
      switch (sch) {
        case 'r': os << "\r"; break;
        case 'n': os << "\n"; break;
        case '\\': os << "\\"; break;
        case '\t': os << "\t"; break;
        case '\"': os << "\""; break;
        default: LOG(FATAL) << "unknown string escape \\" << sch;
      }

I wanted to read string type data from json file after writing it , but an error occurred when sch is character 't',is it a bug?@tqchen
it is ok when I modified the above code as follows:
    ch = is_->get();
    if (ch == '\\') {
      char sch = static_cast<char>(is_->get());
      switch (sch) {
        case 'r': os << "\r"; break;
        case 'n': os << "\n"; break;
        case '\\': os << "\\"; break;
        case 't': os << "\t"; break;
        case '\"': os << "\""; break;
        default: LOG(FATAL) << "unknown string escape \\" << sch;
      }

**Comment by tqchen** [comment]
nice catch, do you mind submit a PR?

**Comment by xianbincheng** [comment]
No,of course not,I will do it in recent days.
