### ISSUE TITLE
Possible collaborations on IO interfaces

### ISSUE THREAD

**Issue by wesm** [dmlc/dmlc-core#273]
hello!

We have been building a small C++11 IO subsystem in Apache Arrow (https://github.com/apache/arrow/tree/master/cpp/src/arrow/io), and we will eventually be in need of cloud storage connectors, which led me here to your implementations of S3, Azure FS, etc. We previous had discussed adopting a filesystem abstraction https://issues.apache.org/jira/browse/ARROW-767

Rather than forking or vendoring your code, I wonder if you would be interested in collaborating on some aspects of this since we have overlapping goals of fast IO in C++. The columnar data structures and zero-copy IO that we are developing may also be of use to some DMLC projects; for example, we want to develop a parallel CSV reader that reads directly into Arrow data structures, with optional features such as dictionary-encoding on read

Let me know what you think!

**Comment by tqchen** [comment]
thanks @wesm for the proposal. Arrow is a great project and there is already some talks about integrating it with some of dmlc libraries, specifically xgboost for the data exchange layer in analytics stack. I would personally love such abstraction coming to C++11

The major requirement for us is maintanace of minimum dependency and ease of installation from our user.  so in short term we could not directly point our project to depend on arrow. It might be possible if we could isolate the filesystem API and make projects depend (which add a bit burden on  isolation, but might be posisble).

**Comment by wesm** [comment]
When you say "minimum dependency" could you elaborate? It seems you are not requiring C++11 yet; do you imagine that will change in the future?

**Comment by tqchen** [comment]
all dmlc projects are now depending on c++11, so yes we would be more than happy to embrace c++11. By minimum dependency I mainly mean minimum library dependencies, for example, dmlc-core only requires libcurl for the https request and it is optional

**Comment by wesm** [comment]
Gotcha, yeah, having Boost as a requirement, for example, could be onerous for some users. We've tried to make building Arrow as painless as we can, and package managers are helping (e.g. Homebrew, conda-forge) so that building from source isn't always necessary

So maybe the simplest thing for me to do would be to fork a little bit of your file system IO code and keep open a dialog about how to share code and help each other out

**Comment by tqchen** [comment]
sgtm
