### ISSUE TITLE
'nullptr' was not declared in this scope

### ISSUE THREAD

**Issue by lyq123180** [dmlc/dmlc-core#290]
with g++ (GCC) 6.3.0，compile the project with this error.
https://stackoverflow.com/questions/10033373/c-error-nullptr-was-not-declared-in-this-scope-in-eclipse-ide
This page says added -std=c++0x to solve this problem for nullstr is  a new characteristic of c11.
I have tried and edit the CMakeList.txt but nothing works.

**Comment by khotilov** [comment]
Check in your cmake log which gcc it has actually picked up, as it might be not the 6.3.0 one.
See https://cmake.org/Wiki/CMake_FAQ#How_do_I_use_a_different_compiler.3F on the ways to make it use the right one.
