### ISSUE TITLE
Reading files under a sub-directory in inputsplit

### ISSUE THREAD

**Issue by saswatac** [dmlc/dmlc-core#303]
Currently only the files under the input parent directory are read, it does not recursively look at the tree under the parent-
https://github.com/dmlc/dmlc-core/blob/master/src/io/input_split_base.cc#L157

Is there a reason behind this? 

@piiswrong 
@ptrendx

**Comment by ptrendx** [comment]
I don't think there is any reason behind this other than current API (you would want to have explicit control whether you read recursively or not). Why would you want that functionality?

**Comment by saswatac** [comment]
I think it may be a common use case that customers data is organized into sub-folders. I agree that if we change, it is better to have explicit control.

I have the following changes in mind-

* add a method ListDirectoryRecursive to https://github.com/dmlc/dmlc-core/blob/master/src/io/filesys.h . All the different file systems should have the same implementation of this method, so add a implementation in filesys.cc. 

* add a bool field to InputSplit to control whether to read recursively. Based on that call ListDirectoryRecursive at https://github.com/dmlc/dmlc-core/blob/master/src/io/input_split_base.cc#L157

* have a new function overloading the inputsplit create function with the new boolean param in https://github.com/dmlc/dmlc-core/blob/master/src/io.cc#L70

Thoughts ?

**Comment by ptrendx** [comment]
Sounds fine.
