### ISSUE TITLE
FieldEntry<float> on g++5.4

### ISSUE THREAD

**Issue by superbobry** [dmlc/dmlc-core#323]
While debugging dmlc/xgboost#2417 I came across a peculiar bug in `std:stof` which, when compiled on Linux with g++5.4, return 0 for `"0.5"`. Interestingly, a simple example outside of XGBoost codebase does not trigger the bug, so I suspect it is caused by some specific combination of flags... wdyt?

```diff
diff --git a/include/dmlc/parameter.h b/include/dmlc/parameter.h
index 73c2b9e..9477bf3 100644
--- a/include/dmlc/parameter.h
+++ b/include/dmlc/parameter.h
@@ -958,6 +958,7 @@ class FieldEntry<float> : public FieldEntryNumeric<FieldEntry<float>, float> {
   typedef FieldEntryNumeric<FieldEntry<float>, float> Parent;
   // override set
   virtual void Set(void *head, const std::string &value) const {
+   std::cout << (float) std::stof("0.5") << std::endl;
     try {
       this->Get(head) = std::stof(value);
     } catch (const std::invalid_argument &) {
```
```
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by superbobry** [comment]
Actually, I've just tried this with g++-7.2 and the truncation is exactly the same.

**Comment by tqchen** [comment]
hmm, maybe we can try other options, like std::istringstream to parse the float

**Comment by superbobry** [comment]
Note: I never got to check this hypothesis, but the issue could be related to locale settings.

**Comment by tqchen** [comment]
ok, I recall @piiswrong mentioned the problem of parsing float in Russian locale

**Comment by thirdwing** [comment]
@superbobry  I think this is really the locale problem. You can try the code below:

```cpp
#include <clocale>
#include <iostream>
 
int main() {
    std::setlocale(LC_NUMERIC, "C");
    std::cout << "C locale " << std::stof("0.5") << std::endl;
    std::setlocale(LC_NUMERIC, "de_DE.UTF-8");
    std::cout << "German locale " << std::stof("0.5") << std::endl;
    std::setlocale(LC_NUMERIC, "C");
    std::cout << "C locale " << std::stof("0.5") << std::endl;
}
```

```
C locale 0.5
German locale 0
C locale 0.5
```

It seems the system locale will be used when calling C code from JVM, and the `C` locale will be used in plain C/C++ program.

**Comment by superbobry** [comment]
@thirdwing yup, this does look like one, but then I think parameter parsing should be locale independent. I doubt people would ever pass `0.5` as `0,5`.

**Comment by thirdwing** [comment]
@superbobry We can also use the neutral locale for Java:

https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#ROOT

**Comment by superbobry** [comment]
Do you mean forcing the locale somewhere in XGBoost code?

**Comment by arzt** [comment]
I solved the issue by setting environment variable `LC_NUMERIC=C` before starting the JVM. Any English locale also works fine.

**Comment by hcho3** [comment]
We should consider merging #351 so that parameters are parsed in locale-independent manner.
