### ISSUE TITLE
Formally Tag Release

### ISSUE THREAD

**Issue by tqchen** [dmlc/dmlc-core#339]
This repo has been used by quite a lot of projects so far. While most of time we rely on changing hashtags in submodule which works fine, it would be great for stable release to point to specific release tags. Do we want to  do formal release on github? Given that the core feature of interest in dmlc-core(logging, json, serialization) has been stable for a while, it might make sense to do so

**Comment by cclauss** [comment]
Agreed.  https://github.com/dmlc/dmlc-core/releases is empty :-(

**Comment by tqchen** [comment]
Thanks @cclauss for the reminder, I have tagged the initial version as 0.3. We will start with a formal release cycle from now on

**Comment by tqchen** [comment]
cc @hcho3
