### ISSUE TITLE
CI is broken: pip not found (see error in comments)

### ISSUE THREAD

**Issue by cjolivier01** [dmlc/dmlc-core#343]
0.02s$ pip install --user cpplint pylint

/Users/travis/.travis/job_stages: line 57: pip: command not found

The command "pip install --user cpplint pylint" failed and exited with 127 during .

Your build has been stopped.

/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found

**Comment by cjolivier01** [comment]
Mac build only

**Comment by hcho3** [comment]
Travis CI has been fixed.
