### ISSUE TITLE
Compile fail on Visual Studio 2015

### ISSUE THREAD

**Issue by snnn** [dmlc/dmlc-core#35]
source code version: e9b5cdb2f63f07f853751db6b92f0fa6565971b9
OS: Windows 10 x64
1>------ Build started: Project: dmlc, Configuration: Release x64 ------
1>  data.cc
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1419): warning C4005: 'vsnprintf': macro redefinition
1>  C:\work\dmlc-core\include\dmlc/base.h(88): note: see previous definition of 'vsnprintf'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1421): fatal error C1189: #error:  Macro definition of vsnprintf conflicts with Standard Library function declaration
1>  io.cc
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1419): warning C4005: 'vsnprintf': macro redefinition
1>  C:\work\dmlc-core\include\dmlc/base.h(88): note: see previous definition of 'vsnprintf'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1421): fatal error C1189: #error:  Macro definition of vsnprintf conflicts with Standard Library function declaration
1>  input_split_base.cc
1>C:\work\dmlc-core\include\dmlc/logging.h(203): warning C4297: 'dmlc::LogMessageFatal::~LogMessageFatal': function assumed not to throw an exception but does
1>  C:\work\dmlc-core\include\dmlc/logging.h(203): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  line_split.cc
1>c:\work\dmlc-core\include\dmlc\./logging.h(203): warning C4297: 'dmlc::LogMessageFatal::~LogMessageFatal': function assumed not to throw an exception but does
1>  c:\work\dmlc-core\include\dmlc\./logging.h(203): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  local_filesys.cc
1>C:\work\dmlc-core\include\dmlc/logging.h(203): warning C4297: 'dmlc::LogMessageFatal::~LogMessageFatal': function assumed not to throw an exception but does
1>  C:\work\dmlc-core\include\dmlc/logging.h(203): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  recordio_split.cc
1>c:\work\dmlc-core\include\dmlc\./logging.h(203): warning C4297: 'dmlc::LogMessageFatal::~LogMessageFatal': function assumed not to throw an exception but does
1>  c:\work\dmlc-core\include\dmlc\./logging.h(203): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
1>  recordio.cc
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1419): warning C4005: 'vsnprintf': macro redefinition
1>  C:\work\dmlc-core\include\dmlc/base.h(88): note: see previous definition of 'vsnprintf'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1421): fatal error C1189: #error:  Macro definition of vsnprintf conflicts with Standard Library function declaration
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by tqchen** [comment]
@hjk41  can you take a look on what was happening?

**Comment by happynear** [comment]
I have fixed this in https://github.com/dmlc/dmlc-core/pull/55 . Please check.
