### ISSUE TITLE
[LOG] Delete backtrace symbol properly

### ISSUE THREAD

**Issue by tqchen** [dmlc/dmlc-core#350]
@larroy seems in the logging backtrace, the list of symbol is not deleted properly.

see the memory leak report in https://github.com/dmlc/tvm/issues/709

**Comment by tqchen** [comment]
see also https://linux.die.net/man/3/backtrace_symbols

**Comment by larroy** [comment]
I will have a look, thanks

**Comment by larroy** [comment]
Hi @tqchen, the symbols are freed as specified in the manpage you linked:

https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/logging.h#L300

Is there something else I'm missing?
Could be an artifact of the sanitizer?

**Comment by tqchen** [comment]
Could it be possible we also need to free each content of the msg? Instead of the array of char ptr itselg

**Comment by tqchen** [comment]
@larroy can you check if that is the reason?

**Comment by larroy** [comment]
I checked, not according to the manpages that I have checked:

backtrace_symbols() attempts to transform a call stack obtained by backtrace() into an array of human-readable strings using dladdr().  The array of
     strings returned has size elements.  It is allocated using malloc() and should be released using free().  There is no need to free the individual
     strings in the array.

So either the docs are wrong, or that particular impl has a problem, or that's not the exact place of the leak, or the libc itself leaks the pointers to those strings.

**Comment by tqchen** [comment]
OK, close this for now
