### ISSUE TITLE
problem with structure inheritance

### ISSUE THREAD

**Issue by albanjiang** [dmlc/dmlc-core#365]
Does dmlc::Parameter support structure inheritance as follow ?
struct a  : public dmlc::Parameter<a> {
   int val0;
  DMLC_DECLARE_PARAMETER(a) {
    DMLC_DECLARE_FIELD(val0);
  }
}
struct b  : public dmlc::Parameter<b> {
   int val1;
  a val2;
  DMLC_DECLARE_PARAMETER(a) {
    DMLC_DECLARE_FIELD(val0);
    DMLC_DECLARE_FIELD(val2);
  }
}

**Comment by tqchen** [comment]
NO, I don't think it support such case, all parameters need to be declared in the final child
