### ISSUE TITLE
UTF-8 Support for TextParser

### ISSUE THREAD

**Issue by anirudh2290** [dmlc/dmlc-core#372]
Currently there is no UTF-8 Support for LibSVM, LibFM or CSV Text parsers. I am currently working on adding UTF-8 support for Text parsers. Since C++ doesnt have great built-in support for UTF-8, I am looking at third-party libraries which provide which provide Unicode support. I am considering ICU currently. Any comments, suggestions, past experience, gotchas about unicode third party libraries or adding unicode support in general is highly appreciated.

**Comment by hcho3** [comment]
Closing this, as apache/incubator-mxnet#9891 has been closed.
