### ISSUE TITLE
Inclusion of "unistd.h" is causing build failure on Windows

### ISSUE THREAD

**Issue by haojin2** [dmlc/dmlc-core#394]
I've updated to use the latest version of dmlc-core in mxnet, but my build on windows is failing due to usage of "unistd.h" in unittest_inputsplit.cc which was added in #389: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10533/9/pipeline. @hcho3 Would you please take a look?

**Comment by hcho3** [comment]
@haojin2 Oops, my bad. I didn't realize that you had to build the unit tests in dmlc-core to build MXNet. I will have to implement `TemporaryDirectory` in Windows API.

**Comment by hcho3** [comment]
I went ahead and make the unit test compatible with Windows.
