### ISSUE TITLE
RowBlock.size seems to be more than the size that RowBlock actually holds

### ISSUE THREAD

**Issue by matricer** [dmlc/dmlc-core#414]
I slightly modifies ${dmlc-core-home}/test/dataiter_test.cc to read a file on HDFS (with **multiple parts** and format of libsvm) and write it to a local file.
 
```cpp
int main(int argc, char *argv[]) {
  if (argc < 4) {
    printf("Usage: filename partid npart [format]\n");
    return 0;
  }
  char libsvm[10] = "libsvm";
  char* format;
  if (argc > 4) {
    format = argv[4];
  } else {
    format = libsvm;
  }
  using namespace dmlc;
  RowBlockIter<index_t> *iter =
      RowBlockIter<index_t>::Create(
          argv[1], atoi(argv[2]), atoi(argv[3]), format);
  double tstart = GetTime();
  size_t bytes_read = 0;
  FILE *fp = fopen("./file-part", "w");
  while (iter->Next()) {
    const RowBlock<index_t> &batch = iter->Value();
    for (size_t i = 0; i < batch.size; ++i) {
      auto row = batch[i];
      if(row.length == 0) continue;
      fprintf(fp, "%f ", row.get_label());
      for (size_t j = 0; j < row.length; ++j) {
        fprintf(fp, "%d ", row.index[j]);
      }
      fprintf(fp, "\n");
    }
    bytes_read += batch.MemCostBytes();
    double tdiff = GetTime() - tstart;
    LOG(INFO) << (bytes_read >> 20UL) <<
        " MB read " << ((bytes_read >> 20UL) / tdiff)<< " MB/sec";
  }
  fclose(fp);
  return 0;
}
```

After compiling, run the command below
./dataiter_test "hdfs:///data/libsvm/avazu/app/valid" 0 7

the last few lines of "file-part" are:
0.000000 10165 156287 233713 301965 358076 410371 439055 534902 536024 556985 565840 595002 783464 797675 861374
0.000000 10165 141273 156287 233713 301965 358076 373075 388415 410371 411218 416678 439055 534902 565840 778407
0.000000 30784 79807 156287 219242 233713 382447 410371 439055 534902 536024 565840 783464 797675 937929 942450
8.000000
the last line is confused, which I think should not exist.

**Comment by hcho3** [comment]
I think dmlc/dmlc-core#452 fixes this. If the problem persists, feel free to re-open this issue.
