### ISSUE TITLE
Fixes recently introduced error with _create_locale and msvcrt

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/dmlc-core#478]
<details>
<summary>The patch</summary>

```patch
From a0b0f7622df29b176a7165c1719037d9c23d66e4 Mon Sep 17 00:00:00 2001
From: KOLANICH <KOLANICH@user.noreply.github.com,>
Date: Tue, 6 Nov 2018 19:55:46 +0300
Subject: [PATCH] Fixed the error with _create_locale by changing the dll for
 stdlib for MinGW-W64.

---
 .gitignore                                    |  1 +
 CMakeLists.txt                                |  8 +++++
 .../workaround_MinGW_MSVCRT_to_MSVCR100.cmake | 33 +++++++++++++++++++
 ...ound_MinGW_MSVCRT_to_MSVCR100_script.cmake |  9 +++++
 test/unittest/CMakeLists.txt                  |  7 ++++
 5 files changed, 58 insertions(+)
 create mode 100644 cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake
 create mode 100644 cmake/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake

diff --git a/.gitignore b/.gitignore
index 707d9ff..c8a77b3 100644
--- a/.gitignore
+++ b/.gitignore
@@ -47,3 +47,4 @@ build
 .idea
 cmake-build-*
 /include/dmlc/build_config.h
+/withMSVCR100.spec
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ea9f659..62cb6b1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -202,6 +202,14 @@ target_link_libraries(dmlc ${dmlccore_LINKER_LIBS})
 target_compile_definitions(dmlc PRIVATE -D_XOPEN_SOURCE=700
   -D_POSIX_SOURCE -D_POSIX_C_SOURCE=200809L -D_DARWIN_C_SOURCE)
 
+if(WIN32)
+  if(MSVC)
+  else(MSVC)
+    if(DMLC_CREATE_LOCALE_PRESENT)
+      include(cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake)
+      workaround_MinGW_MSVCRT_to_MSVCR100(dmlc)
+    endif(DMLC_CREATE_LOCALE_PRESENT)
+  endif(MSVC)
+endif(WIN32)
+
 # ---[ Install Includes
 if(INSTALL_INCLUDE_DIR)
   add_custom_command(TARGET dmlc POST_BUILD
diff --git a/cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake b/cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake
new file mode 100644
index 0000000..cd7c1b7
--- /dev/null
+++ b/cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake
@@ -0,0 +1,33 @@
+﻿# 2018-11-06 Licensed under Unlicense https://unlicense.org/
+# Workarounds a flaw in MinGW-W64 using old msvcrt.dll without some functions somewhen needed.
+# Inspired by https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/gitian/descriptors/windows/gitian-utils.yml?id=b273e8a38b24e716008fa9f51a2b53f20c1f1255#n92 .
+# Unfortunately MinGW-w64 devs like Sourceforge more than getting bug reports and/or pull requests.
+
+set(SCRIPT_FILE_NAME "${CMAKE_CURRENT_LIST_DIR}/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake")
+set(funcName "workaround_MinGW_MSVCRT_to_MSVCR100")
+
+function("${funcName}" target)
+  set(additionalTargetName "workaroundMSVCR100")
+  
+  message(WARNING "${funcName} was used on target \"${target}\". It should be used on dependent targets using that as a native library too, otherwise crashes are likely.")
+  
+  if (TARGET ${additionalTargetName})
+  else()
+    message(STATUS "specFileName is empty")
+    set(specFileName "${CMAKE_BINARY_DIR}/specsWithMSVCR100.spec" CACHE FILENAME "Stores specs" FORCE)
+    add_custom_command(
+      PRE_BUILD
+      OUTPUT "${specFileName}"
+      COMMAND "${CMAKE_COMMAND}" "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}" "-DspecFileName=${specFileName}" -P ${SCRIPT_FILE_NAME}
+      COMMENT "Generating specs into ${specFileName}"
+    )
+    add_custom_target("${additionalTargetName}" DEPENDS "${specFileName}")
+  endif()
+  
+  set_property(
+    TARGET "${target}"
+    APPEND PROPERTY
+      LINK_FLAGS "-specs=${specFileName}"
+  )
+  add_dependencies("${target}" "${additionalTargetName}")
+endfunction()
diff --git a/cmake/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake b/cmake/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake
new file mode 100644
index 0000000..802aca0
--- /dev/null
+++ b/cmake/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake
@@ -0,0 +1,9 @@
+# 2018-11-06 Licensed under Unlicense https://unlicense.org/
+
+execute_process(
+  COMMAND "${CMAKE_CXX_COMPILER}" "-dumpspecs"
+  RESULT_VARIABLE SUCCESS
+  OUTPUT_VARIABLE SPECS
+)
+string(REPLACE "msvcrt" "msvcr100" SPECS "${SPECS}")
+file(WRITE "${specFileName}" "${SPECS}")
diff --git a/test/unittest/CMakeLists.txt b/test/unittest/CMakeLists.txt
index b5339fe..952dbd8 100644
--- a/test/unittest/CMakeLists.txt
+++ b/test/unittest/CMakeLists.txt
@@ -62,3 +62,10 @@ else()
 endif()
 
 add_test(AllTestsInDMLCUnitTests ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/dmlc_unit_tests)
+
+if(WIN32)
+  if(MSVC)
+  else(MSVC)
+    if(DMLC_CREATE_LOCALE_PRESENT)
+      workaround_MinGW_MSVCRT_to_MSVCR100(dmlc_unit_tests)
+    endif(DMLC_CREATE_LOCALE_PRESENT)
+  endif(MSVC)
+endif(WIN32)
+
-- 
2.19.1.windows.1
```
</details>

**Comment by hcho3** [comment]
Can you describe what kind of error you were getting? Currently, we have set up testing for MinGW and Cygwin: https://github.com/dmlc/dmlc-core/blob/master/appveyor.yml

> 2018-11-06 Licensed under Unlicense https://unlicense.org/

This repository is licensed under Apache 2.0, and we follow [Apache Foundation's policy](https://www.apache.org/legal/resolved.html#what-can-we-include-in-an-asf-project-category-a) when it comes to merging code with different licenses. Unlicense is not in the list, so we are unable to accept your contribution. Please consider relicensing to Apache 2.0 (you can remove licensing notice in this case).

Also, please file this as a pull request, so that it is easier to review. Closing this for now.

**Comment by KOLANICH** [comment]
>Can you describe what kind of error you were getting? Currently, we
>have set up testing for MinGW and Cygwin:
>https://github.com/dmlc/dmlc-core/blob/master/appveyor.yml

The error appear only on Windows 7. msvcrt.dll on W7 doesn't have _create_locale and _free_locale.


>Unlicense is not in the list, so we are unable to accept your contribution. Please consider relicensing to Apache 2.0 (you can remove licensing notice in this case).


Unlicense is just a public domain with a disclaimer and an message against copyright. So you are free to relicense when merging.

**Comment by hcho3** [comment]
> msvcrt.dll on W7 doesn't have _create_locale and _free_locale

Then how come does CMake get past this feature check?

https://github.com/dmlc/dmlc-core/blob/a0b11abc037d709b8b59a315fcebc7d8ef5b4adc/CMakeLists.txt#L84

> Unlicense is just a public domain with a disclaimer and an message against copyright. So you are free to relicense when merging.

Okay, so you won't mind if I open a PR on your behalf? I will have remove the licensing notice, thus relicensing your code under Apache 2.0.

**Comment by KOLANICH** [comment]
>Then how come does CMake get past this feature check?

It checks only compilation. The error is in runtime and MinGW links not directly to the dll in system, but via own ar file in own folder.

>Okay, so you won't mind if I open a PR on your behalf? I will have
>remove the licensing notice, thus relicensing your code under Apache
>2.0.

Completely OK, that's why it was put in public domain - to create no licensing problems nowhere.

**Comment by hcho3** [comment]
@KOLANICH I just looked at your patch and had strong feeling that it may be better to remove `_create_locale` and `_free_locale`. I introduced these functions for locale-independent float parsing, but it appears that they cause more headaches than benefits. DMLC-Core already has its [own implementation of `strtof()`](https://github.com/dmlc/dmlc-core/blob/f2afdc7788ee8ed6fd06cc095b6838d4ce61bb5a/src/data/strtonum.h#L39), so let me find a way to add error checking (`std::out_of_range` and `std::invalid_argument`).

**Comment by hcho3** [comment]
@KOLANICH Would you be happy if `_create_locale` and `_free_locale` are removed?

**Comment by KOLANICH** [comment]
>@KOLANICH I just looked at your patch and had strong feeling that it may be better to remove _create_locale and _free_locale.

In fact I'm not sure: this is a long lasting bug in MinGW and it must be fixed, but the devs have chosen to use Sourceforge using reCAPTCHA as hosting and bug tracker. I have tried to sign up there to report the bug (strangely it seems like it is not already reported), but reCaptcha doesn't pass me even after solving 20 screens of buses and road signs.

>I introduced these functions for locale-independent float parsing, but it appears that they cause more headaches than benefits. 

Yes, they do, but Mozilla and TorProject have managed to cope with this.

>@KOLANICH Would you be happy if _create_locale and _free_locale are removed?

IDK: from the one side it seems that I have fixed that and removing these functions is like giving up, from the other side I feel like I may underestimate the problems.

**Comment by hcho3** [comment]
I'm just worried that all projects depending on dmlc-core would be affected by this issue. The locale functions don't seem to be worth the trouble, since they are just used for float parsing.

**Comment by KOLANICH** [comment]
>I'm just worried that all projects depending on dmlc-core would be affected by this issue.

They definitely will if they used anything dependent on dmlc-core as a static lib. For TorProject and Mozilla it is not an issue - they build end product and they build everything themselves.

**Comment by hcho3** [comment]
Yes I know at least two projects that use dmlc-core as static lib: apache/incubator-mxnet and dmlc/xgboost

**Comment by KOLANICH** [comment]
So, are we disabling locale-aware parsing for MinGW, or are we using the workaround, or are we doing both: disable it by default, allow to enable via a CMake cache variable and if it is enabled - use workaround?

**Comment by hcho3** [comment]
No, I am working on implementing locale-independent parsing from scratch.
