### ISSUE TITLE
better support minibatch sgd

### ISSUE THREAD

**Issue by mli** [dmlc/dmlc-core#5]
several suggestions to better support minibatch training:

1. don't assume rowblock.offset[0] is always 0. therefore we can implement Rowblock.Segement(10, 20) which returns a rowblock between row 10 and row 20 with zero cost. see https://github.com/dmlc/wormhole/blob/master/learn/linear/base/minibatch_iter.h#L69

and similarly RowblockContainer.GetBlock(10, 20).

but now we need to change the codes a little bit for nonzero offset[0], one example https://github.com/dmlc/dmlc-core/commit/d2af94ba82b53e29b601ab5dad52cb1ecccab57b

2. let the Parser support the IndexType template. so if we use unsigned as the index type, (true for criteo tera), we don't need to do a memcpy from size_t to unsigned. 

it's not necessary to change the implementation, namely use strtoull to parse the string even use unsigned index type.

3. (not so related) use a static const variable to store the magic number 10UL<<20UL. and sometimes i feel a larger block number size is better.

**Comment by tqchen** [comment]
I think we did not assume offset[0]==0.

I agree that parser can support IndexType, can you do the change?

**Comment by mli** [comment]
i can add the indextype. 

can you add the interface RowBlock.Slice and RowblockContainer.GetBlock, i can do the implementation and testing. there are two choices, [start_row, end_row), vs (start_row, num_row). either is fine for me.

another issue, is it necessary to have multithread parser in libsvm? i didn't see the speedup from 1 thread to 16 threads in my machine.

**Comment by tqchen** [comment]
Seems that was due to your improvements in the parser. I do see speedup with 4 threads

**Comment by tqchen** [comment]
I think we can keep the multi-threading part, and fall back to less thread when necessary

**Comment by tqchen** [comment]
I have added the RowBlock.Slice, there is no need to add slice to RowBlockContainer, you can do 
```
container.GetBlock().Slice(begin, end)
```
