### ISSUE TITLE
mxnet-stable diverges from master

### ISSUE THREAD

**Issue by szha** [dmlc/dmlc-core#507]
@hcho3 https://github.com/dmlc/dmlc-core/compare/master...mxnet-stable?expand=1
#503 needs to be fixed after which we should address the divergence.

**Comment by hcho3** [comment]
@szha Agreed.

**Comment by ptrendx** [comment]
Hi @szha and @hcho3, what is the status of this?

**Comment by hcho3** [comment]
@ptrendx Seeking resolution this week

**Comment by hcho3** [comment]
MXNet now points to the latest master of dmlc-core, thanks to apache/incubator-mxnet#14510
