### ISSUE TITLE
Warning: Redefining fopen64 with std::fopen

### ISSUE THREAD

**Issue by jakirkham** [dmlc/dmlc-core#576]
Am seeing the following warning when building xgboost on Linux and macOS. It seems to be pointing to dmlc-core. So am raising here. Appears there is an issue where `fopen64` is being redefined with `std::fopen`. Build logs linked below as well in case they are of interest.

```C++
/home/conda/feedstock_root/build_artifacts/xgboost_1571964986924/work/dmlc-core/src/build_config.cc:14:6: warning: #warning "Redefining fopen64 with std::fopen" [-Wcpp]
     #warning "Redefining fopen64 with std::fopen"
      ^~~~~~~
```

ref: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=84089

**Comment by hcho3** [comment]
@jakirkham This is expected, since you are using 64-bit systems. Some 32-bit systems define fopen64() and fopen() separately, whereas in 64-bit systems, fopen64() is an alias of fopen().

**Comment by leezu** [comment]
@hcho3 why then print the warning? If this is standard practice, no need to print an extra warning https://github.com/dmlc/dmlc-core/blob/c8f7f9c81dfcf2489d3bbc6d3b2a9200a20fbcde/src/build_config.cc#L10-L16

If not, why do it?

**Comment by hcho3** [comment]
@leezu I didn't add the warning. The warning was added by dmlc/dmlc-core#432.

**Comment by leezu** [comment]
Ok. I suggest to remove the warning: https://github.com/dmlc/dmlc-core/pull/598
