### ISSUE TITLE
[RFC] Enforce CI status checks for master branch

### ISSUE THREAD

**Issue by szha** [dmlc/dmlc-core#597]
Hi,

There have been repeated issues in the CI status for the dmlc-core. I propose that we enforce CI status checks for merging to the master branch as best effort to prevent such issues.

-sz

**Comment by leezu** [comment]
Should the CI be fixed first before enforcing it's status?

We can also consider switching from Travis to Github Actions.

**Comment by comaniac** [comment]
> Should the CI be fixed first before enforcing it's status?
> 
> We can also consider switching from Travis to Github Actions.

Vote to switch to Github Actions. It's pretty convenient and totally free especially for public repos.
