### ISSUE TITLE
missing parentheses in macro

### ISSUE THREAD

**Issue by Light-of-Hers** [dmlc/dmlc-core#620]
https://github.com/dmlc/dmlc-core/blob/ae98c553992eb9f8039fb6e1d17286c0698985de/include/dmlc/logging.h#L192
It may cause some problems that "x" and "y" are not enclosed in parentheses.
For example, in tvm/src/runtime/ndarray.cc:58 `CHECK_EQ(dtype.bits & (dtype.bits - 1), 0);`

**Comment by tqchen** [comment]
Thanks @Light-of-Hers for reporting the issue, @junrushao1994 can you help to send a patch to fix the issue?

**Comment by okuvshynov** [comment]
I can fix it a little later today

**Comment by tqchen** [comment]
https://github.com/dmlc/dmlc-core/pull/621

**Comment by tqchen** [comment]
Thanks @Light-of-Hers @okuvshynov
