### ISSUE TITLE
Memory leak in logging.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/dmlc-core#625]
This line:

https://github.com/dmlc/dmlc-core/blob/9db4b20c868341abe2a9fe52b652f7d9447ed406/include/dmlc/logging.h#L171

Returns a raw pointer of string, which is not collected.  Although it happens only when fatal error occurs, but it's still a c++ exception which can be caught, so deleting it is necessary.  Also, it breaks sanitizer tests.

**Comment by trivialfis** [comment]
Also @okuvshynov if you want to take a look. ;-)

**Comment by junrushao1994** [comment]
ooops...can we use unique ptr instead?

**Comment by hcho3** [comment]
Fixed in #626
