### ISSUE TITLE
cmake option shows errror to build the app

### ISSUE THREAD

**Issue by khaled-rahman** [dmlc/dmlc-core#636]
I am doing the following steps:
```
# mkdir build && cd build
# cmake ..
# make
```
`make` option shows errors like the followings:
```
dmlc-core/include/dmlc/./././json.h:565:50: error: ‘any’ has not been declared
   inline static void ReadAny(JSONReader *reader, any* data) {

dmlc-core/include/dmlc/./././json.h:579:3: error: ‘unordered_map’ in namespace ‘std’ does not name a type
   std::unordered_map<std::type_index, std::string> type_name_;
```

However, `make` on the root directory does not show these errors. It seems there is some kind of dependency problem. Would you please take a look at this issue? This will be helpful. Thank you.

**Comment by hcho3** [comment]
Please post details about your computing environment: OS, C++ compiler, CMake version etc. Also post the log from CMake.

**Comment by khaled-rahman** [comment]
Hi, thank you. I have resolved the problem. Basically, the `any.h`  header file was not included in json.h file unless `DMLC_ENABLE_RTTI` is defined. This is not the default option.
