### ISSUE TITLE
 Crosscompilation fails due to incorrect case

### ISSUE THREAD

**Issue by qjebbs** [dmlc/dmlc-core#646]
Windows is case-insensitive, but when cross-compiling dmlc from Linux with the MinGW tools this causes problems, because the file is named shlwapi.h in lowercase.

include/dmlc/filesystem.h (L21)

```c++
#include <Shlwapi.h>
#pragma comment(lib, "Shlwapi.lib")
```
src/io/local_filesys.cc (L16)
```c++
#include <Windows.h>
```

same issue with this one:
https://github.com/mattn/mruby-pcre-regexp/issues/7

**Comment by hcho3** [comment]
Fixed in https://github.com/dmlc/dmlc-core/pull/673
