### ISSUE TITLE
QNX: unable to determine endianness of your machine

### ISSUE THREAD

**Issue by 987410** [dmlc/dmlc-core#669]
Hello,

I am using dmlc-core in qnx env, when compile dmlc-core, error  "Unable to determine endianness of your machine; use CMake to compile" happened in endian.h:

#ifdef DMLC_CMAKE_LITTLE_ENDIAN
  // If compiled with CMake, use CMake's endian detection logic
  #define DMLC_LITTLE_ENDIAN DMLC_CMAKE_LITTLE_ENDIAN
#else
  #if defined(__APPLE__) || defined(_WIN32)
    #define DMLC_LITTLE_ENDIAN 1
  #elif defined(__GLIBC__) || defined(__GNU_LIBRARY__) \
        || defined(__ANDROID__) || defined(__RISCV__)
    #include <endian.h>
    #define DMLC_LITTLE_ENDIAN (__BYTE_ORDER == __LITTLE_ENDIAN)
  #elif defined(__FreeBSD__) || defined(__OpenBSD__)
    #include <sys/endian.h>
    #define DMLC_LITTLE_ENDIAN (_BYTE_ORDER == _LITTLE_ENDIAN)
  #elif defined(__EMSCRIPTEN__) || defined(__hexagon__)
    #define DMLC_LITTLE_ENDIAN 1
  #elif defined(__sun) || defined(sun)
    #include <sys/isa_defs.h>
    #if defined(_LITTLE_ENDIAN)
      #define DMLC_LITTLE_ENDIAN 1
    #else
      #define DMLC_LITTLE_ENDIAN 0
    #endif
  #else
    #error "Unable to determine endianness of your machine; use CMake to compile"
  #endif
#endif

my question is : 
1. Does dmlm support qnx os?
2. qnx has its own gulliver.h to define endian,  how to use it in dmlc-core?

thanks

**Comment by hcho3** [comment]
As the error message suggests, please use CMake to build.

**Comment by hcho3** [comment]
Fixed in https://github.com/dmlc/dmlc-core/pull/672
