### ISSUE TITLE
support csv format

### ISSUE THREAD

**Issue by mli** [dmlc/dmlc-core#7]
A typical CSV file:

```
Year,Make,Model,Description,Price,Sell 
1997,Ford,E350,"ac, abs, moon",3000.00,40000
```

We assume there are only two types of columns: `real number`, such as Price, and `string`, such as Model and Description. While the category column, such as Year, can be viewed either as real or as string. The parser will use one-shot encoding for string column. 

A user can specify the column format:

```
my_file.csv&label=col[5]&str=col[0-3]&real=col[4]
```

where `col[0-3]` presents column 0, 1, 2, and 3. All `col[0,1,2,3]`, `col[0,1-3]`, `col[0,1-2,3]` are valid and equal.

More options:
- `noheader`, there is no header line
- `sep=\t`, treat `\t` as the separater

**Comment by tqchen** [comment]
Some additional comments:
* The annotation may not cover all the columns, so it can ```select``` the columns specified and ignore the rest

**Comment by tqchen** [comment]
start with a dense column parser at #79

**Comment by AbdealiJK** [comment]
I'd love to contribute CSV readers here.
Can someone explain what this task requires exactly?

As I see it, we'd need a CSV with the following:
 - Which column is a label (added by @tqchen already)
 - Which column is a weight
 - NoHeader/Header option
 - Delimiter option

Questions:
 - Does it also need to be able to read strings ? If yes, how are commas inside strings handled ?
 - Also if strings are needed, We would need to modify `RowBlockContainer` to read in `values` which are not of type real_t - Ideas on doing that efficiently ?
 - If header is given, should the IndexType be set to that string ? Or should it be an integer still ?

**Comment by AbdealiJK** [comment]
So, I've made https://github.com/dmlc/dmlc-core/pull/197 which has an initial version with some additional features.
Two issues:
 - The linux testcase seems to be failing but I have only a Mac so can't figure out why it's failing
 - Any hints on how to accept a range of items in the param ? I can see XGBoost can declare a param as a vector - https://github.com/dmlc/xgboost/blob/master/src/tree/param.h#L148 but I can't seem to be able to set this in csv_parser. It's giving a error:

```
include/dmlc/parameter.h:519:8: error: invalid operands to binary expression ('std::istringstream' (aka 'basic_istringstream<char>') and
      'std::__1::vector<int, std::__1::allocator<int> >')
    is >> this->Get(head);
```

**Comment by AbdealiJK** [comment]
? Is this closed with no plan for support?

**Comment by tqchen** [comment]
closed due to inactivity. As we are getting more issues, it is easier to close stale ones and open new ones when necessary
