### ISSUE TITLE
make lint error

### ISSUE THREAD

**Issue by sharkdtu** [dmlc/dmlc-core#82]
when i run command "make lint", i get following errors. Is there something i need to configure?
python scripts/lint.py dmlc "all" include src scripts
Traceback (most recent call last):
  File "scripts/lint.py", line 13, in <module>
    from pylint import epylint
ImportError: No module named pylint
make: *** [lint] Error 1

**Comment by tqchen** [comment]
It depends on pylint, you can install it via```pip install pylint```
